#!/bin/bash

GCI_VERSION=1.0
GCI_BUILD=1.0.1

ARG1=$1
ARG2=$2

source /etc/os-release
OS=$ID
OS_VERSION=$VERSION_ID

GCE_LATEST="22.4.0"


echo ""
echo -n "OS DETECTED:    " 
echo -n $OS" "
echo $OS_VERSION
echo ""

if [[ $EUID -ne 0 ]]; then
    echo "GCI requires root privileges"
    exit 1
fi



if [ "$ARG1" == "install" ] && [ "$OS" == "debian" ] && [ "$OS_VERSION" == "11" ] && [ "$ARG2" == "" ]; then
    source include/GCE_22.4.0/Debian_11/install
fi

