#!/bin/bash

set -e

GCI_VERSION=1.0
GCI_BUILD=1.0.8

ARG1=$1
ARG2=$2

source /etc/os-release
OS=$ID
OS_VERSION=$VERSION_ID

GCI_PATH=$(dirname "$0")

GCE_LATEST="22.4.0"

echo -e "\n##################################################"
echo -e "\n GCI - Version: $GCI_VERSION   Build: $GCI_BUILD\n"
echo -e " Greenbone Community Installer\n"
echo -e "####################################################"



echo -e "\n\n"
echo -n " OS DETECTED:    " 
echo -n $OS" "
echo $OS_VERSION
echo ""

if [[ $EUID -ne 0 ]]; then
    echo "GCI requires root privileges"
    exit 1
fi



if [ "$ARG1" == "install" ] && [ "$ARG2" == "" ]; then
    
    if [ "$OS" == "debian" ] && [ "$OS_VERSION" == "11" ]; then
    	source $GCI_PATH/include/GCE_22.4.0/Debian_11/install
    else
        echo -e "\n OS NOT SUPPORTED\n"
    fi


elif [ "$ARG1" == "uninstall" ]; then
    echo ""
    echo " Function not yet implemented"
    echo ""



else
    echo ""



fi

