#!/bin/bash

set -e

echo -n "Do you want to install Greenbone Community Edition 22.4.0? (Y/n) "
read RET

if [ "$RET" == "no" ] || [ "$RET" == "NO" ] || [ "$RET" == "No" ] || \
    [ "$RET" == "n" ] || [ "$RET" == "N" ]; then
    exit
elif [ "$RET" == "yes" ] || [ "$RET" == "YES" ] || [ "$RET" == "Yes" ] || \
        [ "$RET" == "Y" ] || [ "$RET" == "y" ] || [ "$RET" == "" ]; then
   
    export GCE_VERSION=22.4.0
    export SOURCE_DIR=/opt/GCE_$GCE_VERSION/src
    export INSTALL_PREFIX=/opt/GCE_$GCE_VERSION   

    useradd -r -M -U -s /usr/sbin/nologin gvm || true
    
    apt update
    apt -y install wget

    mkdir -p /opt/GCE_$GCE_VERSION
    mkdir -p /opt/GCE_$GCE_VERSION/src

    apt install -y --no-install-recommends \
	build-essential \
  	curl \
  	cmake \
  	pkg-config \
  	python3 \
  	python3-pip \
  	gnupg

    curl -f -L https://www.greenbone.net/GBCommunitySigningKey.asc -o /tmp/GBCommunitySigningKey.asc
    gpg --import /tmp/GBCommunitySigningKey.asc


############################################ BEGIN - GVM-LIBS ###########################################

    apt install -y \
        libglib2.0-dev \
  	    libgpgme-dev \
  	    libgnutls28-dev \
  	    uuid-dev \
  	    libssh-gcrypt-dev \
  	    libhiredis-dev \
  	    libxml2-dev \
  	    libpcap-dev \
  	    libnet1-dev \
  	    libpaho-mqtt-dev \
	    libldap2-dev \
        libradcli-dev


    
    curl -f -L https://github.com/greenbone/gvm-libs/archive/refs/tags/v$GCE_VERSION.tar.gz -o /opt/GCE_$GCE_VERSION/src/gvm-libs-$GCE_VERSION.tar.gz
    curl -f -L https://github.com/greenbone/gvm-libs/releases/download/v$GCE_VERSION/gvm-libs-$GCE_VERSION.tar.gz.asc -o /opt/GCE_$GCE_VERSION/src/gvm-libs-$GCE_VERSION.tar.gz.asc        
    gpg --verify /opt/GCE_$GCE_VERSION/src/gvm-libs-$GCE_VERSION.tar.gz.asc /opt/GCE_$GCE_VERSION/src/gvm-libs-$GCE_VERSION.tar.gz
        
    tar -C /opt/GCE_$GCE_VERSION/src  -xvzf /opt/GCE_$GCE_VERSION/src/gvm-libs-$GCE_VERSION.tar.gz
    rm /opt/GCE_$GCE_VERSION/src/gvm-libs-$GCE_VERSION.tar.gz
    rm /opt/GCE_$GCE_VERSION/src/gvm-libs-$GCE_VERSION.tar.gz.asc
    cd /opt/GCE_$GCE_VERSION/src/gvm-libs-$GCE_VERSION
    mkdir -p build
    cd build    


    cmake /opt/GCE_$GCE_VERSION/src/gvm-libs-$GCE_VERSION \
        -DCMAKE_INSTALL_PREFIX=/opt/GCE_$GCE_VERSION \
        -DCMAKE_BUILD_TYPE=Release \
        -DSYSCONFDIR=/etc \
        -DLOCALSTATEDIR=/var

    make -j$(nproc)
    make install 

############################################ END - GVM-LIBS ###########################################




############################################ BEGIN - GVMD ###########################################
    export PKG_CONFIG_PATH=/opt/GCE_$GCE_VERSION/lib/pkgconfig:$PKG_CONFIG_PATH

    apt install -y \
        libglib2.0-dev \
        libgnutls28-dev \
        libpq-dev \
        postgresql-server-dev-13 \
        libical-dev \
        xsltproc \
        rsync \
        libbsd-dev \
        libgpgme-dev

    apt install -y --no-install-recommends \
        texlive-latex-extra \
        texlive-fonts-recommended \
        xmlstarlet \
        zip \
        rpm \
        fakeroot \
        dpkg \
        nsis \
        gnupg \
        gpgsm \
        wget \
        sshpass \
        openssh-client \
        socat \
        snmp \
        python3 \
        smbclient \
        python3-lxml \
        gnutls-bin \
        xml-twig-tools

curl -f -L https://github.com/greenbone/gvmd/archive/refs/tags/v$GCE_VERSION.tar.gz -o /opt/GCE_$GCE_VERSION/src/gvmd-$GCE_VERSION.tar.gz
tar -C /opt/GCE_$GCE_VERSION/src -xvzf /opt/GCE_$GCE_VERSION/src/gvmd-$GCE_VERSION.tar.gz
rm /opt/GCE_$GCE_VERSION/src/gvmd-$GCE_VERSION.tar.gz

cd /opt/GCE_$GCE_VERSION/src/gvmd-$GCE_VERSION
mkdir -p build
cd build

cmake /opt/GCE_$GCE_VERSION/src/gvmd-$GCE_VERSION \
  -DCMAKE_INSTALL_PREFIX=/opt/GCE_$GCE_VERSION \
  -DCMAKE_BUILD_TYPE=Release \
  -DLOCALSTATEDIR=/var \
  -DSYSCONFDIR=/etc \
  -DGVM_DATA_DIR=/var \
  -DGVMD_RUN_DIR=/run/gvmd \
  -DOPENVAS_DEFAULT_SOCKET=/run/ospd/ospd-openvas.sock \
  -DGVM_FEED_LOCK_PATH=/var/lib/gvm/feed-update.lock \
  -DSYSTEMD_SERVICE_DIR=/lib/systemd/system \
  -DLOGROTATE_DIR=/etc/logrotate.d

make -j$(nproc)
make install

############################################ END - GVMD ###########################################




############################################ BEGIN - PG-GVM ###########################################

apt install -y \
        libglib2.0-dev \
        postgresql-server-dev-13 \
        libical-dev

curl -f -L https://github.com/greenbone/pg-gvm/archive/refs/tags/v$GCE_VERSION.tar.gz -o /opt/GCE_$GCE_VERSION/src/pg-gvm-$GCE_VERSION.tar.gz
tar -C /opt/GCE_$GCE_VERSION/src -xvzf /opt/GCE_$GCE_VERSION/src/pg-gvm-$GCE_VERSION.tar.gz
rm /opt/GCE_$GCE_VERSION/src/pg-gvm-$GCE_VERSION.tar.gz

cd /opt/GCE_$GCE_VERSION/src/pg-gvm-$GCE_VERSION
mkdir -p build
cd build

cmake /opt/GCE_$GCE_VERSION/src/pg-gvm-$GCE_VERSION \
  -DCMAKE_BUILD_TYPE=Release

make -j$(nproc)
make install

############################################ END - PG-GVM ###########################################




############################################ BEGIN - GSA ###########################################

apt -y install lsb-release

export NODE_VERSION=node_14.x
export KEYRING=/usr/share/keyrings/nodesource.gpg
export DISTRIBUTION="$(lsb_release -s -c)"

curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | sudo tee "$KEYRING" >/dev/null
gpg --no-default-keyring --keyring "$KEYRING" --list-keys

echo "deb [signed-by=$KEYRING] https://deb.nodesource.com/$NODE_VERSION $DISTRIBUTION main" | sudo tee /etc/apt/sources.list.d/nodesource.list
echo "deb-src [signed-by=$KEYRING] https://deb.nodesource.com/$NODE_VERSION $DISTRIBUTION main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list


sudo apt update
sudo apt install -y nodejs


curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt update
sudo apt install -y yarn


curl -f -L https://github.com/greenbone/gsa/archive/refs/tags/v$GCE_VERSION.tar.gz -o /opt/GCE_$GCE_VERSION/src/gsa-$GCE_VERSION.tar.gz
tar -C /opt/GCE_$GCE_VERSION/src -xvzf /opt/GCE_$GCE_VERSION/src/gsa-$GCE_VERSION.tar.gz
rm $SOURCE_DIR/gsa-$GCE_VERSION.tar.gz

cd $SOURCE_DIR/gsa-$GCE_VERSION
rm -rf build

yarn
yarn build


mkdir -p $INSTALL_PREFIX/share/gvm/gsad/web/
cp -r build/* $INSTALL_PREFIX/share/gvm/gsad/web/


apt install -y \
    libmicrohttpd-dev \
    libxml2-dev \
    libglib2.0-dev \
    libgnutls28-dev






############################################ END - GSA ###########################################

else
    exit
fi
